#shib-sp configuration
# also see shib_vault
shib_sp_cert:           "{{ vault_shib_sp_cert }}"
shib_sp_key:            "{{ vault_shib_sp_key }}"
shib_idp_metadata_xml:  "{{ vault_shib_idp_metadata_xml}}"
shib_entity_id:         "https://findit.library.jhu.edu/shibboleth"
# NOTE: overriding because the official repo is having mirror issues at present (9/13/17)
# getting alternate urls from:
# http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/x86_64/shibboleth-2.6.0-2.1.x86_64.rpm.mirrorlist
# because the official list ( https://mirrors.opensuse.org/ )
# is mostly mirrors of the openSUSE project, and not the repos we need
shib_repo_baseurl:      "https://ftp.gwdg.de/pub/opensuse/repositories/security:/shibboleth/CentOS_7/"



