# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# setup vars
project:        "findit-ansible"
version:        "0.1.0"
login_user:     "deploy"

# ssh vars
ssh_port: 22
# uncomment after first run (if not 22):
# ansible_ssh_port: "{{ ssh_port }}"

mode:                         "deploy" # dev || deploy

app_repo:                     "git@github.com:jhu-sheridan-libraries/umlaut_jh.git" 
app_branch:                   "development"
app_name:                     "findit"
app_user:                     "{{ app_name }}"
app_group:                    "{{ app_user }}"
base_deploy_dir:              "/opt"
deploy_dir:                   "{{ base_deploy_dir }}/{{ app_name }}"

# deploy keys vars
deploy_private_key:           "{{ vault_deploy_private_key }}"
deploy_public_key:            "{{ vault_deploy_public_key }}"
deploy_user:                  "{{ login_user }}"
deploy_key_name:              "findit_deploy_key"
deploy_key_full_path:         "/home/{{ deploy_user }}/.ssh/{{ deploy_key_name }}"

# apache vars
apache_config_file:           "/etc/{{ apache_service }}/conf.d/01_{{ hostname }}.conf"
# apache_config_template:     "templates/apache.conf.j2"

# rails vars
rails_env:                    "development"

ssh_pub_keys:
 - ~/.ssh/findit-ansible/findit-ansible_dev.pub

#shib
shib_sp_cert:           "{{ vault_shib_sp_cert }}"
shib_sp_key:            "{{ vault_shib_sp_key }}"
shib_idp_metadata_xml:  "{{ vault_shib_idp_metadata_xml}}"
shib_entity_id:         "findit.library.jhu.edu"
# NOTE: overriding because the official repo is having mirror issues at present (9/13/17)
# getting alternate urls from:
# http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/x86_64/shibboleth-2.6.0-2.1.x86_64.rpm.mirrorlist
# because the official list ( https://mirrors.opensuse.org/ )
# is mostly mirrors of the openSUSE project, and not the repos we need
shib_repo_baseurl:      "http://ftp.gwdg.de/pub/opensuse/repositories/security:/shibboleth/CentOS_7/"

sfx_url: 'http://sfx.library.jhu.edu:8000/sfxlcl41'

blacklight_url: 'https://catalyst-test.library.jhu.edu'

borrow_direct_horizon_borrower_lookup_url: "{{ vault_borrow_direct_horizon__borrower_lookup_url }}"
borrow_direct_api_key: "{{ vault_borrow_direct_api_key }}"
borrow_direct_api_base: "{{ vault_borrow_direct_api_base }}"
